spring:
  application:
    name: shiro
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.190.209:3306/shiro?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
server:
  port: 8080
  servlet:
    context-path: /shiro
mybatis:
  type-aliases-package: com.orichalcos.entity
  mapper-locations: classpath:mapping/*Mapper.xml